import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ubaid Ahmed",
  description: "Generated by create next app",
};
// Nunito - 400 for paragraph 
// sans-serif - 700 for heading
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/Images/avatarimg.png" />
        <meta name="description" content={metadata.description} />
       
      </head>
      <body className={`${inter.className} font-serif bg-dark`}>
        <Providers >
        {children}
        </Providers>
        </body>
    </html>
  );
}
